version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    target-branch: "24.04"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "24.04"
    schedule:
      interval: weekly
